# Generated by Django 6.0.4 on 2026-04-26 07:14

import config.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Recommended size: square image, e.g., 500x500px.', null=True, upload_to=config.utils.UploadToPath('avatars'), verbose_name='Profile Photo')),
                ('position', models.CharField(help_text='e.g., Tracker, Program Coordinator, Fund Partner', max_length=255, verbose_name='Role in the Ecosystem')),
                ('position_en', models.CharField(help_text='e.g., Tracker, Program Coordinator, Fund Partner', max_length=255, null=True, verbose_name='Role in the Ecosystem')),
                ('position_uz', models.CharField(help_text='e.g., Tracker, Program Coordinator, Fund Partner', max_length=255, null=True, verbose_name='Role in the Ecosystem')),
                ('position_ru', models.CharField(help_text='e.g., Tracker, Program Coordinator, Fund Partner', max_length=255, null=True, verbose_name='Role in the Ecosystem')),
                ('bio', models.TextField(blank=True, help_text='Describe your experience, project focus, and how you can help.', verbose_name='Bio and Expertise')),
                ('bio_en', models.TextField(blank=True, help_text='Describe your experience, project focus, and how you can help.', null=True, verbose_name='Bio and Expertise')),
                ('bio_uz', models.TextField(blank=True, help_text='Describe your experience, project focus, and how you can help.', null=True, verbose_name='Bio and Expertise')),
                ('bio_ru', models.TextField(blank=True, help_text='Describe your experience, project focus, and how you can help.', null=True, verbose_name='Bio and Expertise')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('telegram_handle', models.CharField(blank=True, help_text='Without @, e.g., durov', max_length=100, null=True, verbose_name='Telegram Username')),
                ('is_published', models.BooleanField(default=False, help_text='Uncheck to temporarily hide the profile from the public catalog', verbose_name='Published on site')),
                ('show_on_main_page', models.BooleanField(default=False, help_text='If checked, this builder will be featured on the main landing page.', verbose_name='Show on Main Page')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('affiliated_entities', models.ManyToManyField(blank=True, help_text='Select the universities, incubators, or programs this builder is involved with.', related_name='affiliated_builders', to='hub.ecosystementity', verbose_name='Affiliated Organizations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Builder Profile',
                'verbose_name_plural': 'Builder Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
