# Generated by Django 6.0.4 on 2026-04-26 08:19

import config.utils
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderprofile',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=config.utils.UploadToPath('avatars/thumbnails'), verbose_name='Profile Photo Thumbnail'),
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Recommended size: square image, e.g., 500x500px.', null=True, upload_to=config.utils.UploadToPath('avatars'), verbose_name='Profile Photo'),
        ),
    ]
