# Generated by Django 6.0.4 on 2026-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_builderprofile_photo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builderprofile',
            name='position',
            field=models.CharField(blank=True, help_text='e.g., Tracker, Program Coordinator, Fund Partner', max_length=255, verbose_name='Role in the Ecosystem'),
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='position_en',
            field=models.CharField(blank=True, help_text='e.g., Tracker, Program Coordinator, Fund Partner', max_length=255, null=True, verbose_name='Role in the Ecosystem'),
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='position_ru',
            field=models.CharField(blank=True, help_text='e.g., Tracker, Program Coordinator, Fund Partner', max_length=255, null=True, verbose_name='Role in the Ecosystem'),
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='position_uz',
            field=models.CharField(blank=True, help_text='e.g., Tracker, Program Coordinator, Fund Partner', max_length=255, null=True, verbose_name='Role in the Ecosystem'),
        ),
    ]
