# Generated by Django 6.0.4 on 2026-04-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_builderprofile_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('na', 'Not Specified')], default='na', max_length=6, verbose_name='Gender'),
        ),
    ]
