# Generated by Django 6.0.4 on 2026-05-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_builderprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderprofile',
            name='expertise',
            field=models.TextField(blank=True, help_text='Brief description of areas of expertise.', max_length=500, verbose_name='Expertise'),
        ),
        migrations.AddField(
            model_name='builderprofile',
            name='is_expert',
            field=models.BooleanField(default=False, help_text='Mark this profile as an expert.', verbose_name='Expert'),
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Describe yourself in a few sentences, including your background and involvement in the ecosystem.', verbose_name='Short Bio'),
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='bio_en',
            field=models.TextField(blank=True, help_text='Describe yourself in a few sentences, including your background and involvement in the ecosystem.', null=True, verbose_name='Short Bio'),
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='bio_ru',
            field=models.TextField(blank=True, help_text='Describe yourself in a few sentences, including your background and involvement in the ecosystem.', null=True, verbose_name='Short Bio'),
        ),
        migrations.AlterField(
            model_name='builderprofile',
            name='bio_uz',
            field=models.TextField(blank=True, help_text='Describe yourself in a few sentences, including your background and involvement in the ecosystem.', null=True, verbose_name='Short Bio'),
        ),
    ]
