# Generated by Django 6.0.4 on 2026-05-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_builderprofile_expertise_builderprofile_is_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderprofile',
            name='expertise_en',
            field=models.TextField(blank=True, help_text='Brief description of areas of expertise.', max_length=500, null=True, verbose_name='Expertise'),
        ),
        migrations.AddField(
            model_name='builderprofile',
            name='expertise_ru',
            field=models.TextField(blank=True, help_text='Brief description of areas of expertise.', max_length=500, null=True, verbose_name='Expertise'),
        ),
        migrations.AddField(
            model_name='builderprofile',
            name='expertise_uz',
            field=models.TextField(blank=True, help_text='Brief description of areas of expertise.', max_length=500, null=True, verbose_name='Expertise'),
        ),
    ]
