# Generated by Django 6.0.4 on 2026-05-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_builderprofile_expertise_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderprofile',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='First Name (RU)'),
        ),
        migrations.AddField(
            model_name='builderprofile',
            name='first_name_uz',
            field=models.CharField(blank=True, max_length=150, verbose_name='First Name (UZ)'),
        ),
        migrations.AddField(
            model_name='builderprofile',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last Name (RU)'),
        ),
        migrations.AddField(
            model_name='builderprofile',
            name='last_name_uz',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last Name (UZ)'),
        ),
    ]
