# Generated by Django 6.0.4 on 2026-04-26 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Category Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Category Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('content', models.TextField(help_text='Main text of the article, or a detailed description if this is a downloadable file/video.', verbose_name='Content / Description')),
                ('content_en', models.TextField(help_text='Main text of the article, or a detailed description if this is a downloadable file/video.', null=True, verbose_name='Content / Description')),
                ('content_uz', models.TextField(help_text='Main text of the article, or a detailed description if this is a downloadable file/video.', null=True, verbose_name='Content / Description')),
                ('content_ru', models.TextField(help_text='Main text of the article, or a detailed description if this is a downloadable file/video.', null=True, verbose_name='Content / Description')),
                ('attached_file', models.FileField(blank=True, help_text='e.g., PDF report, Excel template, or presentation.', null=True, upload_to='wiki/files/', verbose_name='Attached File')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo link.', null=True, verbose_name='Video URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_resources', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='wiki.resourcecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
