# Generated by Django 6.0.4 on 2026-05-08 19:34

import config.utils
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=config.utils.UploadToPath('logos/resources'), verbose_name='Logo'),
        ),
    ]
