# Generated by Django 6.0.4 on 2026-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_resource_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='show_on_quickinfo',
            field=models.BooleanField(default=False, help_text="Show in the quick info carousel on the main page (requires 'quickinfo' category).", verbose_name='Show on Quick Info'),
        ),
    ]
