# Generated by Django 6.0.4 on 2026-05-14 04:30

import config.utils
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_add_show_on_quickinfo_to_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='original_link',
            field=models.URLField(blank=True, help_text="Link to the original source or full article. Used in Quick Info as a 'See more' link.", null=True, verbose_name='Original Link'),
        ),
        migrations.AddField(
            model_name='resource',
            name='quickinfo_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=config.utils.UploadToPath('quickinfo/images'), verbose_name='Quick Info Image'),
        ),
    ]
