# Generated by Django 6.0.4 on 2026-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallToActionAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_en', models.TextField(null=True, verbose_name='Message')),
                ('message_uz', models.TextField(null=True, verbose_name='Message')),
                ('message_ru', models.TextField(null=True, verbose_name='Message')),
                ('link', models.CharField(help_text='Internal path (e.g. /en/programs/) or full external URL.', max_length=500, verbose_name='Link')),
                ('link_text', models.CharField(max_length=100, verbose_name='Link Text')),
                ('link_text_en', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('link_text_uz', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('link_text_ru', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Call to Action Announcement',
                'verbose_name_plural': 'Call to Action Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_en', models.TextField(null=True, verbose_name='Message')),
                ('message_uz', models.TextField(null=True, verbose_name='Message')),
                ('message_ru', models.TextField(null=True, verbose_name='Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Technical Announcement',
                'verbose_name_plural': 'Technical Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
