# Generated by Django 6.0.4 on 2026-04-26 08:21

import config.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Leave blank to auto-generate', max_length=100, unique=True, verbose_name='Slug (URL identifying name)')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EcosystemEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('has_physical_space', models.BooleanField(default=True, help_text='Uncheck this if it is a purely virtual program.', verbose_name='Has Physical Space')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Abbreviation / Short Name')),
                ('short_name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation / Short Name')),
                ('short_name_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation / Short Name')),
                ('short_name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation / Short Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('city', models.CharField(default='Tashkent', max_length=100, verbose_name='City')),
                ('city_en', models.CharField(default='Tashkent', max_length=100, null=True, verbose_name='City')),
                ('city_uz', models.CharField(default='Tashkent', max_length=100, null=True, verbose_name='City')),
                ('city_ru', models.CharField(default='Tashkent', max_length=100, null=True, verbose_name='City')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=config.utils.UploadToPath('logos/entities'), verbose_name='Logo')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Founded Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('organizers', models.ManyToManyField(blank=True, help_text='Organizations that run or host this program/entity.', related_name='organized_entities', to='hub.ecosystementity', verbose_name='Organizers')),
                ('parent', models.ForeignKey(blank=True, help_text='E.g., An incubator belongs to a university.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hub.ecosystementity', verbose_name='Parent Organization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='hub.entitycategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Ecosystem Entity',
                'verbose_name_plural': 'Ecosystem Entities',
                'ordering': ['category__name', 'name'],
            },
        ),
    ]
