# Generated by Django 6.0.4 on 2026-04-26 08:50

import config.utils
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_ecosystementity_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystementity',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=config.utils.UploadToPath('logos/entities/thumbnails'), verbose_name='Logo Thumbnail'),
        ),
        migrations.AlterField(
            model_name='ecosystementity',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=config.utils.UploadToPath('logos/entities'), verbose_name='Logo'),
        ),
    ]
