# Generated by Django 6.0.4 on 2026-04-28 03:45

import config.utils
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_ecosystementity_logo_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ecosystementity',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Used for programs. Recommended: 1200×630px.', null=True, upload_to=config.utils.UploadToPath('covers/entities'), verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='ecosystementity',
            name='end_date',
            field=models.DateField(blank=True, help_text='Program end date.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='ecosystementity',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Deadline'),
        ),
        migrations.AddField(
            model_name='ecosystementity',
            name='start_date',
            field=models.DateField(blank=True, help_text='Program start date.', null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='ecosystementity',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Regions covered by this program.', related_name='entities', to='hub.region', verbose_name='Regions'),
        ),
    ]
