# Generated by Django 6.0.4 on 2026-04-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_region_ecosystementity_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
