# Generated by Django 6.0.4 on 2026-04-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_region_name_en_region_name_ru_region_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystementity',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('accepting', 'Accepting Applications'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], help_text='Program lifecycle status. Leave blank for non-program entities.', max_length=20, verbose_name='Status'),
        ),
    ]
