# Generated by Django 6.0.4 on 2026-05-01 17:55

import config.utils
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_ecosystementity_status'),
        ('users', '0004_builderprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(help_text='e.g. 1, 2, 3 — used for ordering', verbose_name='Cycle Number')),
                ('title', models.CharField(blank=True, help_text="Optional label, e.g. 'Cohort 3' or 'Spring 2024'", max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Cycle-specific description or notes.', verbose_name='Notes')),
                ('status', models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('accepting', 'Accepting Applications'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='Registration Deadline')),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Recommended: 1200×630px.', null=True, upload_to=config.utils.UploadToPath('covers/cycles'), verbose_name='Cover Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('coordinators', models.ManyToManyField(blank=True, help_text='People contributing to this specific cycle.', related_name='coordinated_cycles', to='users.builderprofile', verbose_name='Contributors')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='hub.ecosystementity', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Cycle',
                'verbose_name_plural': 'Program Cycles',
                'ordering': ['-cycle_number'],
                'unique_together': {('program', 'cycle_number')},
            },
        ),
    ]
