# Generated by Django 6.0.4 on 2026-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_add_program_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecosystementity',
            name='coordinators',
        ),
        migrations.RemoveField(
            model_name='ecosystementity',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='ecosystementity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ecosystementity',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='ecosystementity',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='ecosystementity',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='ecosystementity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='ecosystementity',
            name='status',
        ),
        migrations.AddField(
            model_name='programcycle',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text='Organizations that run or host this cycle.', related_name='organized_cycles', to='hub.ecosystementity', verbose_name='Organizers'),
        ),
        migrations.AddField(
            model_name='programcycle',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Regions covered by this cycle.', related_name='cycles', to='hub.region', verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='cycle_number',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-assigned if left blank.', verbose_name='Cycle Number'),
        ),
    ]
