# Generated by Django 6.0.4 on 2026-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_programcycle_translations'),
        ('users', '0004_builderprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcycle',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='People contributing to this specific cycle.', related_name='contributed_cycles', to='users.builderprofile', verbose_name='Contributors'),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='description_en',
            field=models.TextField(blank=True, help_text='Cycle-specific description or notes.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Cycle-specific description or notes.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Cycle-specific description or notes.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='title_en',
            field=models.CharField(blank=True, help_text="Optional label, e.g. 'Cohort 3' or 'Spring 2024'", max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='title_ru',
            field=models.CharField(blank=True, help_text="Optional label, e.g. 'Cohort 3' or 'Spring 2024'", max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='title_uz',
            field=models.CharField(blank=True, help_text="Optional label, e.g. 'Cohort 3' or 'Spring 2024'", max_length=100, null=True, verbose_name='Title'),
        ),
    ]
