# Generated by Django 6.0.4 on 2026-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0016_add_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='label_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('accepting', 'Registration'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status'),
        ),
    ]
