# Generated by Django 6.0.4 on 2026-05-12 17:00

import config.utils
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_alter_customfield_label_en_and_more'),
        ('users', '0005_builderprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('short_title', models.CharField(blank=True, max_length=50, verbose_name='Short Title / Abbreviation')),
                ('short_title_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Title / Abbreviation')),
                ('short_title_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Title / Abbreviation')),
                ('short_title_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Title / Abbreviation')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from title.', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=config.utils.UploadToPath('logos/communities'), verbose_name='Logo')),
                ('logo_thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=config.utils.UploadToPath('logos/communities/thumbnails'), verbose_name='Logo Thumbnail')),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Recommended: 1200×630px.', null=True, upload_to=config.utils.UploadToPath('covers/communities'), verbose_name='Cover Image')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('telegram_handle', models.CharField(blank=True, help_text='Without @, e.g., mycomminity', max_length=100, verbose_name='Telegram Channel / Group')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinators', models.ManyToManyField(blank=True, related_name='coordinated_communities', to='users.builderprofile', verbose_name='Coordinators')),
                ('member_organizations', models.ManyToManyField(blank=True, help_text='Organizations that are part of this community.', related_name='member_of_communities', to='hub.ecosystementity', verbose_name='Member Organizations')),
                ('members', models.ManyToManyField(blank=True, help_text='Individual people who are part of this community.', related_name='communities', to='users.builderprofile', verbose_name='Members')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ['title'],
            },
        ),
    ]
