# Generated by Django 6.0.4 on 2026-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_community_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this community in the featured block on the home page.', verbose_name='Featured on main page'),
        ),
        migrations.AddField(
            model_name='programcycle',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this cycle in the featured block on the home page.', verbose_name='Featured on main page'),
        ),
    ]
