# Generated by Django 6.0.4 on 2026-05-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_featured_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcycle',
            name='address',
            field=models.CharField(blank=True, help_text='Physical venue or address for this cycle.', max_length=255, verbose_name='Event Address'),
        ),
    ]
