# Generated by Django 6.0.4 on 2026-05-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_add_address_to_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcycle',
            name='address_en',
            field=models.CharField(blank=True, help_text='Physical venue or address for this cycle.', max_length=255, null=True, verbose_name='Event Address'),
        ),
        migrations.AddField(
            model_name='programcycle',
            name='address_ru',
            field=models.CharField(blank=True, help_text='Physical venue or address for this cycle.', max_length=255, null=True, verbose_name='Event Address'),
        ),
        migrations.AddField(
            model_name='programcycle',
            name='address_uz',
            field=models.CharField(blank=True, help_text='Physical venue or address for this cycle.', max_length=255, null=True, verbose_name='Event Address'),
        ),
    ]
