# Generated by Django 6.0.4 on 2026-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0022_community_formed_year_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='member_organizations',
        ),
        migrations.AddField(
            model_name='community',
            name='supporting_organizations',
            field=models.ManyToManyField(blank=True, help_text='Organizations that support this community.', related_name='supporting_communities', to='hub.ecosystementity', verbose_name='Supporting Organizations'),
        ),
    ]
