# Generated by Django 6.0.4 on 2026-05-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0023_rename_member_organizations_to_supporting_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystementity',
            name='show_on_main',
            field=models.BooleanField(default=False, help_text='Show this entity in the featured block on the home page. Only active entities will be shown.', verbose_name='Featured on main page'),
        ),
    ]
